apiVersion: v1
kind: ConfigMap
metadata:
  name: twodaymovie-config
  labels:
    app: twodaymovie
data:
  PORT: "8080"
  FLASK_DEBUG: "0"
  TMDB_WATCH_REGION: "US"
  OFFICIAL_URL: "https://twodaymovie.onrender.com/"
  WEB_CONCURRENCY: "2"
  WEB_THREADS: "4"
