"""Replace year_movies + series_shows from the curated 1975–2027 list."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

# Movies by release year (series stripped / moved to SERIES below).
YEAR_MOVIES: dict[int, list[str]] = {
    # Pre-2000 classics
    1975: ["Xala"],
    1985: ["Ran"],
    1987: ["Yeelen"],
    1988: ["Akira", "Grave of the Fireflies"],
    1991: ["Raise the Red Lantern", "A Brighter Summer Day"],
    1992: ["Sarafina!"],
    1993: ["Farewell My Concubine", "Sonatine"],
    1994: ["To Live", "Chungking Express"],
    1997: [
        "Hana-bi",
        "Princess Mononoke",
        "12 Storeys",
        "Children of Heaven",
    ],
    1998: [
        "Run Lola Run",
        "After Life",
        "Central Station",
    ],
    2000: [
        "Gladiator",
        "Memento",
        "Crouching Tiger, Hidden Dragon",
        "Requiem for a Dream",
        "Cast Away",
        "Almost Famous",
        "Traffic",
        "American Psycho",
        "Erin Brockovich",
        "X-Men",
        "Snatch",
        "Chicken Run",
        "In the Mood for Love",
        "You Can Count on Me",
        "Wonder Boys",
        "Amores Perros",
        "Billy Elliot",
        "O Brother, Where Art Thou?",
        "Battle Royale",
        "Unbreakable",
        "Best in Show",
        "Meet the Parents",
        "Dancer in the Dark",
        "Remember the Titans",
        "Chocolat",
        "Girlfight",
        "Yi Yi",
        "Peppermint Candy",
    ],
    2001: [
        "The Lord of the Rings: The Fellowship of the Ring",
        "Amélie",
        "Mulholland Drive",
        "Shrek",
        "Monsters, Inc.",
        "Black Hawk Down",
        "A Beautiful Mind",
        "Ocean's Eleven",
        "Training Day",
        "Y Tu Mamá También",
        "Donnie Darko",
        "The Royal Tenenbaums",
        "Moulin Rouge!",
        "Harry Potter and the Sorcerer's Stone",
        "In the Bedroom",
        "Gosford Park",
        "Spirited Away",
        "Lagaan",
    ],
    2002: [
        "The Lord of the Rings: The Two Towers",
        "City of God",
        "Minority Report",
        "Catch Me If You Can",
        "Chicago",
        "Talk to Her",
        "The Pianist",
        "Adaptation",
        "Punch-Drunk Love",
        "About Schmidt",
        "Road to Perdition",
        "Spider-Man",
        "Signs",
        "Lilo & Stitch",
        "The Bourne Identity",
        "Panic Room",
        "8 Mile",
        "My Big Fat Greek Wedding",
        "Frida",
        "Ice Age",
        "The Ring",
        "Hero",
        "Infernal Affairs",
    ],
    2003: [
        "The Lord of the Rings: The Return of the King",
        "Kill Bill: Vol. 1",
        "Finding Nemo",
        "Lost in Translation",
        "Mystic River",
        "Big Fish",
        "School of Rock",
        "American Splendor",
        "Whale Rider",
        "X2",
        "Oldboy",
        "Memories of Murder",
        "Pirates of the Caribbean: The Curse of the Black Pearl",
        "Love Actually",
        "Cold Mountain",
        "The Last Samurai",
        "The Barbarian Invasions",
        "Save the Green Planet!",
        "Wonderful Days",
    ],
    2004: [
        "Eternal Sunshine of the Spotless Mind",
        "The Incredibles",
        "Kill Bill: Vol. 2",
        "Sideways",
        "Million Dollar Baby",
        "Mean Girls",
        "Shaun of the Dead",
        "Hotel Rwanda",
        "The Aviator",
        "Collateral",
        "Spider-Man 2",
        "House of Flying Daggers",
        "The Motorcycle Diaries",
        "Napoleon Dynamite",
        "National Treasure",
        "Downfall",
        "Moolaadé",
        "Howl's Moving Castle",
        "The Notebook",
        "Man on Fire",
    ],
    2005: [
        "Brokeback Mountain",
        "Batman Begins",
        "Crash",
        "Munich",
        "Capote",
        "Sin City",
        "Pride & Prejudice",
        "King Kong",
        "Walk the Line",
        "A History of Violence",
        "Wallace & Gromit: The Curse of the Were-Rabbit",
        "Match Point",
        "The Constant Gardener",
        "Serenity",
        "Tsotsi",
        "The Maid",
        "C.R.A.Z.Y.",
        "The 40-Year-Old Virgin",
        "Kung Fu Hustle",
    ],
    2006: [
        "The Departed",
        "Pan's Labyrinth",
        "Children of Men",
        "Little Miss Sunshine",
        "The Prestige",
        "Babel",
        "The Queen",
        "Casino Royale",
        "An Inconvenient Truth",
        "Borat",
        "Dreamgirls",
        "The Devil Wears Prada",
        "Marie Antoinette",
        "The Lives of Others",
        "Still Life",
        "Nobody Knows",
    ],
    2007: [
        "No Country for Old Men",
        "There Will Be Blood",
        "Zodiac",
        "Ratatouille",
        "Juno",
        "Michael Clayton",
        "Into the Wild",
        "Atonement",
        "Superbad",
        "Once",
        "4 Months, 3 Weeks and 2 Days",
        "Elite Squad",
        "The Diving Bell and the Butterfly",
        "Persepolis",
        "The Bourne Ultimatum",
    ],
    2008: [
        "The Dark Knight",
        "WALL-E",
        "Slumdog Millionaire",
        "In Bruges",
        "Milk",
        "Frost/Nixon",
        "Iron Man",
        "Let the Right One In",
        "Gran Torino",
        "Departures",
        "The Chaser",
        "Old Partner",
        "Gomorrah",
        "Rachel Getting Married",
    ],
    2009: [
        "Avatar",
        "Inglourious Basterds",
        "Up",
        "The Hurt Locker",
        "A Serious Man",
        "Precious",
        "District 9",
        "Star Trek",
        "An Education",
        "Moon",
        "500 Days of Summer",
        "Mother",
        "3 Idiots",
        "The Secret in Their Eyes",
        "The White Ribbon",
        "Zombieland",
    ],
    2010: [
        "Inception",
        "The Social Network",
        "Toy Story 3",
        "Black Swan",
        "True Grit",
        "The King's Speech",
        "127 Hours",
        "The Fighter",
        "I Saw the Devil",
        "The Man from Nowhere",
        "Poetry",
        "Incendies",
        "Uncle Boonmee Who Can Recall His Past Lives",
        "The Illusionist",
        "Chico & Rita",
        "How to Train Your Dragon",
    ],
    2011: [
        "Drive",
        "The Tree of Life",
        "Midnight in Paris",
        "Hugo",
        "The Artist",
        "Moneyball",
        "Bridesmaids",
        "A Separation",
        "Melancholia",
        "The King of Pigs",
        "Warrior",
    ],
    2012: [
        "Zero Dark Thirty",
        "Argo",
        "Django Unchained",
        "Life of Pi",
        "Lincoln",
        "Silver Linings Playbook",
        "Amour",
        "The Avengers",
        "Ah Boys to Men",
        "The Act of Killing",
        "No",
        "Skyfall",
        "Les Misérables",
    ],
    2013: [
        "12 Years a Slave",
        "Gravity",
        "Her",
        "American Hustle",
        "The Wolf of Wall Street",
        "Ida",
        "Frances Ha",
        "Ilo Ilo",
        "The Grandmaster",
        "A Touch of Sin",
        "The Missing Picture",
        "The Great Beauty",
        "The Fake",
        "Half of a Yellow Sun",
        "Blue Jasmine",
        "Nebraska",
        "iNumber Number",
    ],
    2014: [
        "Whiplash",
        "Birdman",
        "Boyhood",
        "The Grand Budapest Hotel",
        "Gone Girl",
        "Interstellar",
        "Nightcrawler",
        "Selma",
        "Foxcatcher",
        "Force Majeure",
        "Timbuktu",
        "Mommy",
        "Wild Tales",
        "Guardians of the Galaxy",
    ],
    2015: [
        "Mad Max: Fury Road",
        "The Revenant",
        "Spotlight",
        "Room",
        "Inside Out",
        "The Big Short",
        "Carol",
        "Sicario",
        "Ex Machina",
        "Bridge of Spies",
        "Baahubali: The Beginning",
        "Ixcanul",
        "Shaun the Sheep Movie",
        "Star Wars: The Force Awakens",
    ],
    2016: [
        "Moonlight",
        "La La Land",
        "Arrival",
        "Manchester by the Sea",
        "Hell or High Water",
        "The Handmaiden",
        "Your Name.",
        "A Silent Voice",
        "Train to Busan",
        "Big Fish & Begonia",
        "Toni Erdmann",
        "Dangal",
        "Zootopia",
        "Deadpool",
        "Love O2O",
    ],
    2017: [
        "Get Out",
        "Lady Bird",
        "Call Me by Your Name",
        "Dunkirk",
        "The Shape of Water",
        "Three Billboards Outside Ebbing, Missouri",
        "Wolf Warrior 2",
        "A Taxi Driver",
        "The Square",
        "The Wound",
        "Have a Nice Day",
        "Loving Vincent",
        "Coco",
        "Logan",
    ],
    2018: [
        "Roma",
        "Black Panther",
        "A Star Is Born",
        "The Favourite",
        "BlacKkKlansman",
        "Spider-Man: Into the Spider-Verse",
        "Shoplifters",
        "Burning",
        "Rafiki",
        "A Land Imagined",
        "Cold War",
        "Lionheart",
    ],
    2019: [
        "Parasite",
        "Once Upon a Time in Hollywood",
        "Marriage Story",
        "1917",
        "Joker",
        "The Irishman",
        "Little Women",
        "Uncut Gems",
        "Jojo Rabbit",
        "Knives Out",
        "Better Days",
        "So Long, My Son",
        "Ne Zha",
        "The Wandering Earth",
        "Atlantics",
        "You Will Die at Twenty",
        "Wet Season",
        "Article 15",
        "Klaus",
        "Weathering with You",
        "Avengers: Endgame",
    ],
    2020: [
        "Nomadland",
        "Sound of Metal",
        "Minari",
        "Promising Young Woman",
        "Da 5 Bloods",
        "Soul",
        "The Trial of the Chicago 7",
        "First Cow",
        "Palm Springs",
        "Tenet",
        "Wolfwalkers",
        "The White Tiger",
    ],
    2021: [
        "CODA",
        "Dune",
        "The Power of the Dog",
        "Drive My Car",
        "Belfast",
        "Licorice Pizza",
        "King Richard",
        "New Gods: Nezha Reborn",
        "Raya and the Last Dragon",
        "Ainbo: Spirit of the Amazon",
        "No Time to Die",
        "Spider-Man: No Way Home",
        "Encanto",
    ],
    2022: [
        "Everything Everywhere All at Once",
        "Top Gun: Maverick",
        "The Banshees of Inisherin",
        "Tár",
        "The Fabelmans",
        "All Quiet on the Western Front",
        "Aftersun",
        "Decision to Leave",
        "RRR",
        "Ajoomma",
        "Return to Seoul",
        "First Love",
        "Suzume",
        "The Batman",
        "Nope",
    ],
    2023: [
        "Oppenheimer",
        "Poor Things",
        "Killers of the Flower Moon",
        "Barbie",
        "The Zone of Interest",
        "Anatomy of a Fall",
        "Past Lives",
        "The Holdovers",
        "Perfect Days",
        "Godzilla Minus One",
        "Jiva!",
        "The Boy and the Heron",
        "Saltburn",
        "Society of the Snow",
        "Fallen Leaves",
    ],
    2024: [
        "The Brutalist",
        "Anora",
        "Conclave",
        "The Substance",
        "A Real Pain",
        "Nickel Boys",
        "Emilia Pérez",
        "Sing Sing",
        "Dune: Part Two",
        "Challengers",
        "Wicked",
        "A Complete Unknown",
        "Nosferatu",
        "Flow",
        "Hanuman",
        "The Wild Robot",
        "Furiosa: A Mad Max Saga",
    ],
    2025: [
        "One Battle After Another",
        "Sinners",
        "Weapons",
        "Bugonia",
        "Wake Up Dead Man",
        "Materialists",
        "Ne Zha 2",
        "The King of Kings",
        "KPop Demon Hunters",
        "The Life of Chuck",
        "No Other Land",
        "Sentimental Value",
        "Hamnet",
    ],
    2026: [
        "Project Hail Mary",
        "28 Years Later: The Bone Temple",
        "Obsession",
        "Michael",
        "The Drama",
        "The Furious",
        "Backrooms",
        "Coyote vs. Acme",
        "Zootopia 2",
        "The Super Mario Galaxy Movie",
        "Digger",
        "Clayface",
        "Street Fighter",
        "Wildwood",
        "Whalefall",
        "The Hunger Games: Sunrise on the Reaping",
        "Predator: Badlands",
        "A Christmas Carol",
        "Now You See Me: Now You Don't",
        "Wicker",
        "Hexe",
        "The Cat in the Hat",
        "Avengers: Doomsday",
        "Dune: Part Three",
        "Violent Night 2",
        "Ray Gunn",
        "Jumanji: Open World",
        "Mortal Kombat II",
    ],
    2027: [
        "Children of Blood and Bone",
        "The Beekeeper 2",
        "Air Bud Returns",
        "Pendulum",
        "The Chronicles of Narnia: The Magician's Nephew",
        "The Master and Margarita",
        "Avengers: Secret Wars",
        "Star Wars: Starfighter",
        "Teenage Mutant Ninja Turtles: Mutant Mayhem 2",
        "The Exorcist",
        "The Bluey Movie",
        "The New Simpsons Movie",
        "Untitled Blair Witch Film",
        "Untitled DreamWorks Animated Event Film",
        "The Great Beyond",
        "Frozen III",
        "Gremlins 3",
        "Charlie and the Chocolate Factory",
        "The Lord of the Rings: The Hunt for Gollum",
        "Untitled Pixar Film",
    ],
}

# TV / anime series (start year). End year None when ongoing / unknown.
SERIES: list[dict] = [
    {"title": "Neon Genesis Evangelion", "start": 1995, "end": 1995},
    {"title": "Cowboy Bebop", "start": 1998, "end": 1999},
    {"title": "One Piece", "start": 1999, "end": None},
    {"title": "Gilmore Girls", "start": 2000, "end": 2007},
    {"title": "Curb Your Enthusiasm", "start": 2000, "end": 2024},
    {"title": "Six Feet Under", "start": 2001, "end": 2005},
    {"title": "24", "start": 2001, "end": 2010},
    {"title": "The Shield", "start": 2002, "end": 2008},
    {"title": "The Wire", "start": 2002, "end": 2008},
    {"title": "Arrested Development", "start": 2003, "end": 2019},
    {"title": "Lost", "start": 2004, "end": 2010},
    {"title": "Deadwood", "start": 2004, "end": 2006},
    {"title": "Friday Night Lights", "start": 2006, "end": 2011},
    {"title": "Sherlock", "start": 2010, "end": 2017},
    {"title": "Borgen", "start": 2010, "end": 2022},
    {"title": "Empresses in the Palace", "start": 2011, "end": 2012},
    {"title": "The Bridge", "start": 2011, "end": 2018},
    {"title": "Line of Duty", "start": 2012, "end": 2021},
    {"title": "Peaky Blinders", "start": 2013, "end": 2022},
    {"title": "Call My Agent!", "start": 2015, "end": 2020},
    {"title": "Broadchurch", "start": 2013, "end": 2017},
    {"title": "Happy Valley", "start": 2014, "end": 2023},
    {"title": "Nirvana in Fire", "start": 2015, "end": 2015},
    {"title": "Reply 1988", "start": 2015, "end": 2016},
    {"title": "Bino and Fino", "start": 2010, "end": None},
    {"title": "Club de Cuervos", "start": 2015, "end": 2019},
    {"title": "Narcos", "start": 2015, "end": 2017},
    {"title": "Midnight Diner", "start": 2009, "end": 2019},
    {"title": "Fleabag", "start": 2016, "end": 2019},
    {"title": "3%", "start": 2016, "end": 2020},
    {"title": "Westworld", "start": 2016, "end": 2022},
    {"title": "Mr. Sunshine", "start": 2018, "end": 2018},
    {"title": "Money Heist", "start": 2017, "end": 2021},
    {"title": "Dark", "start": 2017, "end": 2020},
    {"title": "Babylon Berlin", "start": 2017, "end": None},
    {"title": "Story of Yanxi Palace", "start": 2018, "end": 2018},
    {"title": "Sky Castle", "start": 2018, "end": 2019},
    {"title": "My Mister", "start": 2018, "end": 2018},
    {"title": "Sacred Games", "start": 2018, "end": 2019},
    {"title": "Killing Eve", "start": 2018, "end": 2022},
    {"title": "Chernobyl", "start": 2019, "end": 2019},
    {"title": "Kingdom", "start": 2019, "end": 2021},
    {"title": "Crash Landing on You", "start": 2019, "end": 2020},
    {"title": "Delhi Crime", "start": 2019, "end": None},
    {"title": "Kota Factory", "start": 2019, "end": 2021},
    {"title": "Made in Heaven", "start": 2019, "end": None},
    {"title": "Demon Slayer: Kimetsu no Yaiba", "start": 2019, "end": None},
    {"title": "It's Okay to Not Be Okay", "start": 2020, "end": 2020},
    {"title": "Alice in Borderland", "start": 2020, "end": None},
    {"title": "Queen Sono", "start": 2020, "end": 2020},
    {"title": "Blood & Water", "start": 2020, "end": None},
    {"title": "Kings of Jo'burg", "start": 2020, "end": None},
    {"title": "Followers", "start": 2020, "end": 2020},
    {"title": "Dark Desire", "start": 2020, "end": 2022},
    {"title": "Squid Game", "start": 2021, "end": None},
    {"title": "Hellbound", "start": 2021, "end": None},
    {"title": "Move to Heaven", "start": 2021, "end": 2021},
    {"title": "D.P.", "start": 2021, "end": 2023},
    {"title": "Vincenzo", "start": 2021, "end": 2021},
    {"title": "Lupin", "start": 2021, "end": None},
    {"title": "The Glory", "start": 2022, "end": 2023},
    {"title": "All of Us Are Dead", "start": 2022, "end": None},
    {"title": "Extraordinary Attorney Woo", "start": 2022, "end": None},
    {"title": "Tokyo Vice", "start": 2022, "end": 2024},
    {"title": "Shōgun", "start": 2024, "end": None},
    {"title": "Blade Runner 2099", "start": 2026, "end": None},
    {"title": "Carrie", "start": 2026, "end": None},
    {"title": "VisionQuest", "start": 2026, "end": None},
    {"title": "A Knight of the Seven Kingdoms", "start": 2026, "end": None},
    {"title": "Pride & Prejudice", "start": 2026, "end": None},
    {"title": "Crystal Lake", "start": 2026, "end": None},
    {"title": "Yellowjackets", "start": 2021, "end": 2026},
]


def rewrite_year_movies() -> None:
    path = ROOT / "data" / "year_movies.py"
    lines = [
        '"""Curated 2daymovie library: notable films (classics through 2027)."""',
        "",
        "YEAR_MOVIES = {",
    ]
    for year in sorted(YEAR_MOVIES):
        lines.append(f"    {year}: [")
        seen = set()
        for title in YEAR_MOVIES[year]:
            key = re.sub(r"[^a-z0-9]+", "", title.lower())
            if key in seen:
                continue
            seen.add(key)
            lines.append(f"        {title!r},")
        lines.append("    ],")
    lines.append("}")
    lines.extend(
        [
            "",
            "",
            "def all_years() -> list[int]:",
            "    return sorted(YEAR_MOVIES.keys(), reverse=True)",
            "",
            "",
            "def titles_for_year(year: int) -> list[str]:",
            "    return list(YEAR_MOVIES.get(year, []))",
            "",
            "",
            "def total_titles() -> int:",
            "    return sum(len(v) for v in YEAR_MOVIES.values())",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {path} ({sum(len(v) for v in YEAR_MOVIES.values())} movies)")


def rewrite_series() -> None:
    path = ROOT / "data" / "series_shows.py"
    lines = [
        '"""Curated TV series with on-site official trailer embeds."""',
        "",
        "from __future__ import annotations",
        "",
        "SERIES_SHOWS: list[dict] = [",
    ]
    seen = set()
    for row in sorted(SERIES, key=lambda r: (r["start"], r["title"])):
        key = re.sub(r"[^a-z0-9]+", "", row["title"].lower())
        if key in seen:
            continue
        seen.add(key)
        end = "None" if row["end"] is None else str(row["end"])
        lines.append(
            f'    {{"title": {row["title"]!r}, "start": {row["start"]}, "end": {end}}},'
        )
    lines.append("]")
    lines.extend(
        [
            "",
            "",
            "def all_series() -> list[dict]:",
            "    return list(SERIES_SHOWS)",
            "",
            "",
            "def total_series() -> int:",
            "    return len(SERIES_SHOWS)",
            "",
            "",
            "def years_span_label(show: dict) -> str:",
            '    start = show.get("start")',
            '    end = show.get("end")',
            "    if not start:",
            '        return ""',
            "    if end is None:",
            '        return f"{start}–"',
            "    if end == start:",
            '        return str(start)',
            '    return f"{start}–{end}"',
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {path} ({len(seen)} series)")


def rewrite_upcoming() -> None:
    path = ROOT / "data" / "upcoming.py"
    movies_2026 = YEAR_MOVIES[2026]
    movies_2027 = YEAR_MOVIES[2027]
    series_upcoming = [
        s["title"]
        for s in SERIES
        if s["start"] >= 2026 or (s.get("end") and s["end"] >= 2026)
    ]
    # Keep Yellowjackets / Lupin as upcoming season mentions
    for extra in ["Lupin", "Yellowjackets"]:
        if extra not in series_upcoming:
            series_upcoming.append(extra)

    content = f'''"""Upcoming 2026–2027 movies and series (titles only; linked via catalogs)."""

UPCOMING_MOVIES_2026 = {movies_2026!r}

UPCOMING_MOVIES_2027 = {movies_2027!r}

UPCOMING_SERIES = {series_upcoming!r}
'''
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path}")


if __name__ == "__main__":
    rewrite_year_movies()
    rewrite_series()
    rewrite_upcoming()
