"""One-shot: merge ADDITIONS into year_movies.py with case-insensitive dedupe."""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from data.year_movies import YEAR_MOVIES  # noqa: E402

ADDITIONS: dict[int, list[str]] = {
    2000: [
        "Unbreakable",
        "Best in Show",
        "Meet the Parents",
        "Dancer in the Dark",
        "The Contender",
        "Remember the Titans",
        "Chocolat",
        "Girlfight",
        "The Cell",
        "Space Cowboys",
        "Frequency",
        "High Fidelity",
        "Center Stage",
        "What Lies Beneath",
        "Vertical Limit",
        "Miss Congeniality",
        "The Patriot",
        "Nurse Betty",
        "Bring It On",
        "Thirteen Days",
    ],
    2001: [
        "Zoolander",
        "Bridget Jones's Diary",
        "Ghost World",
        "The Others",
        "Vanilla Sky",
        "Sexy Beast",
        "Iris",
        "Enemy at the Gates",
        "Rat Race",
        "Jurassic Park III",
        "Spy Kids",
        "Legally Blonde",
        "Jeepers Creepers",
        "A.I. Artificial Intelligence",
        "Pearl Harbor",
        "The Fast and the Furious",
        "Kate & Leopold",
        "Monster's Ball",
        "Rush Hour 2",
        "Hedwig and the Angry Inch",
    ],
    2002: [
        "The Bourne Identity",
        "Panic Room",
        "8 Mile",
        "My Big Fat Greek Wedding",
        "Igby Goes Down",
        "Frida",
        "Solaris",
        "Ice Age",
        "Femme Fatale",
        "The Ring",
        "Auto Focus",
        "The Good Girl",
        "Real Women Have Curves",
        "Dirty Pretty Things",
        "Rabbit-Proof Fence",
        "Blue Crush",
        "Changing Lanes",
        "One Hour Photo",
        "About a Boy",
        "The Quiet American",
    ],
    2003: [
        "Lost in La Mancha",
        "Down with Love",
        "Freaky Friday",
        "Love Actually",
        "Under the Tuscan Sun",
        "Bruce Almighty",
        "Runaway Jury",
        "Something's Gotta Give",
        "Cold Mountain",
        "Girl with a Pearl Earring",
        "Shattered Glass",
        "Matchstick Men",
        "Thirteen",
        "Bad Santa",
        "Camp",
        "Owning Mahowny",
        "Le Divorce",
        "The Fog of War",
        "Intolerable Cruelty",
        "Seabiscuit",
    ],
    2004: [
        "Closer",
        "Vera Drake",
        "Maria Full of Grace",
        "Garden State",
        "The Notebook",
        "We Don't Live Here Anymore",
        "Bad Education",
        "The Machinist",
        "Dawn of the Dead",
        "Anchorman: The Legend of Ron Burgundy",
        "Dodgeball: A True Underdog Story",
        "The Manchurian Candidate",
        "Alfie",
        "Man on Fire",
        "King Arthur",
        "Shrek 2",
        "National Treasure",
        "I Heart Huckabees",
        "Friday Night Lights",
        "The Village",
    ],
    2005: [
        "Broken Flowers",
        "The Squid and the Whale",
        "Jarhead",
        "Cinderella Man",
        "Hustle & Flow",
        "Mad Hot Ballroom",
        "Layer Cake",
        "The 40-Year-Old Virgin",
        "Kung Fu Hustle",
        "Transamerica",
        "North Country",
        "Green Street Hooligans",
        "Yes",
        "The New World",
        "Nine Lives",
        "Melinda and Melinda",
        "Mr. & Mrs. Smith",
        "Wedding Crashers",
        "Constantine",
        "Red Eye",
    ],
    2006: [
        "Blood Diamond",
        "World Trade Center",
        "Rocky Balboa",
        "Thank You for Smoking",
        "Little Children",
        "Idiocracy",
        "Kinky Boots",
        "Marie Antoinette",
        "The Devil Wears Prada",
        "Clerks II",
        "Miami Vice",
        "The Illusionist",
        "A Scanner Darkly",
        "Old Joy",
        "Apocalypto",
        "Cars",
        "Talladega Nights: The Ballad of Ricky Bobby",
        "Inside Man",
        "The Science of Sleep",
        "Flags of Our Fathers",
    ],
    2007: [
        "Knocked Up",
        "Hairspray",
        "Sunshine",
        "Grindhouse",
        "Charlie Wilson's War",
        "Lars and the Real Girl",
        "Waitress",
        "Rocket Science",
        "Away from Her",
        "Control",
        "La Vie en Rose",
        "This Is England",
        "Death Proof",
        "Enchanted",
        "The Savages",
        "Reservation Road",
        "Margot at the Wedding",
        "In the Valley of Elah",
        "Talk to Me",
        "Music and Lyrics",
    ],
    2008: [
        "Kung Fu Panda",
        "Burn After Reading",
        "Happy-Go-Lucky",
        "Changeling",
        "The Reader",
        "Defiance",
        "Australia",
        "Tell No One",
        "Hunger",
        "Snow Angels",
        "4 Months, 3 Weeks and 2 Days",
        "JCVD",
        "Cadillac Records",
        "Ghost Town",
        "Pineapple Express",
        "Role Models",
        "Wanted",
        "Taken",
        "Forgetting Sarah Marshall",
        "The Strangers",
    ],
    2009: [
        "Up in the Air",
        "The Messenger",
        "Crazy Heart",
        "Bright Star",
        "Fish Tank",
        "Nine",
        "The Road",
        "Julie & Julia",
        "Adventureland",
        "The Informant!",
        "Away We Go",
        "Duplicity",
        "I Love You, Man",
        "Whip It",
        "Bad Lieutenant: Port of Call New Orleans",
        "Public Enemies",
        "Watchmen",
        "The Blind Side",
        "Harry Potter and the Half-Blood Prince",
        "Funny People",
    ],
    2010: [
        "The Ghost Writer",
        "Get Low",
        "Greenberg",
        "Somewhere",
        "Buried",
        "Another Year",
        "Barney's Version",
        "The American",
        "Conviction",
        "Fair Game",
        "Made in Dagenham",
        "The Girl with the Dragon Tattoo",
        "Restrepo",
        "Waiting for Superman",
        "Tangled",
        "Despicable Me",
        "Easy A",
        "Let Me In",
        "The Kids Are All Right",
        "Please Give",
    ],
    2011: [
        "Contagion",
        "Margin Call",
        "Beginners",
        "Young Adult",
        "The Ides of March",
        "Hanna",
        "Crazy, Stupid, Love.",
        "Le Havre",
        "Certified Copy",
        "A Dangerous Method",
        "Carnage",
        "J. Edgar",
        "Weekend",
        "Martha Marcy May Marlene",
        "Rango",
        "Super 8",
        "The Guard",
        "Win Win",
        "Source Code",
        "Like Crazy",
    ],
    2012: [
        "The Cabin in the Woods",
        "Killing Them Softly",
        "Wreck-It Ralph",
        "Seven Psychopaths",
        "Compliance",
        "The Sessions",
        "Rust and Bone",
        "Barbara",
        "No",
        "Neighboring Sounds",
        "Safety Not Guaranteed",
        "Bernie",
        "Magic Mike",
        "21 Jump Street",
        "Ted",
        "ParaNorman",
        "Sleepwalk with Me",
        "Killer Joe",
        "Arbitrage",
        "The Grey",
    ],
    2013: [
        "The Spectacular Now",
        "Mud",
        "Only Lovers Left Alive",
        "Blue Ruin",
        "A Touch of Sin",
        "Stories We Tell",
        "The Way Way Back",
        "About Time",
        "Philomena",
        "Saving Mr. Banks",
        "Rush",
        "In a World...",
        "Lone Survivor",
        "Coherence",
        "The World's End",
        "This Is the End",
        "The Place Beyond the Pines",
        "Don Jon",
        "Enough Said",
        "August: Osage County",
    ],
    2014: [
        "Edge of Tomorrow",
        "Calvary",
        "The Babadook",
        "Obvious Child",
        "Big Hero 6",
        "John Wick",
        "The Lego Movie",
        "We Are the Best!",
        "Leviathan",
        "Winter Sleep",
        "The Skeleton Twins",
        "Listen Up Philip",
        "Song of the Sea",
        "X-Men: Days of Future Past",
        "Dear White People",
        "Inherent Vice",
        "The Theory of Everything",
        "St. Vincent",
        "Chef",
        "Exodus: Gods and Kings",
    ],
    2015: [
        "The Martian",
        "Bone Tomahawk",
        "Tangerine",
        "Dope",
        "45 Years",
        "Youth",
        "The Lobster",
        "Krisha",
        "The Diary of a Teenage Girl",
        "Slow West",
        "Trainwreck",
        "Spy",
        "The Gift",
        "What We Do in the Shadows",
        "Amy",
        "Cop Car",
        "Room 237",
        "Mission: Impossible - Rogue Nation",
        "Ant-Man",
        "Spectre",
    ],
    2016: [
        "Sing Street",
        "Weiner",
        "The Witch",
        "Swiss Army Man",
        "Kubo and the Two Strings",
        "The Neon Demon",
        "Loving",
        "Lion",
        "13th",
        "Doctor Strange",
        "Everybody Wants Some!!",
        "Certain Women",
        "Paterson",
        "Little Sister",
        "Moana",
        "Cameraperson",
        "The Edge of Seventeen",
        "Popstar: Never Stop Never Stopping",
        "Don't Breathe",
        "Cafe Society",
    ],
    2017: [
        "Wonder Woman",
        "Thor: Ragnarok",
        "War for the Planet of the Apes",
        "The Big Sick",
        "Colossal",
        "The Meyerowitz Stories (New and Selected)",
        "Brawl in Cell Block 99",
        "It Comes at Night",
        "Personal Shopper",
        "Okja",
        "Ingrid Goes West",
        "Columbus",
        "The Beguiled",
        "Lady Macbeth",
        "Wonderstruck",
        "Beatriz at Dinner",
        "Detroit",
        "Loving Vincent",
        "Wonder",
        "Mudbound",
    ],
    2018: [
        "Avengers: Infinity War",
        "A Quiet Place",
        "Isle of Dogs",
        "First Man",
        "Suspiria",
        "The Rider",
        "We the Animals",
        "Leave No Trace",
        "Mandy",
        "Private Life",
        "Burning",
        "Happy as Lazzaro",
        "Zama",
        "Madeline's Madeline",
        "Can You Ever Forgive Me?",
        "The Old Man & the Gun",
        "Paddington 2",
        "Free Solo",
        "Minding the Gap",
        "Crazy Rich Asians",
    ],
    2019: [
        "Toy Story 4",
        "Ad Astra",
        "Dolemite Is My Name",
        "Harriet",
        "Doctor Sleep",
        "High Life",
        "The Souvenir",
        "Honey Boy",
        "Long Shot",
        "Rocketman",
        "Klaus",
        "The Report",
        "Motherless Brooklyn",
        "Last Christmas",
        "A Hidden Life",
        "Judy",
        "Bombshell",
        "Richard Jewell",
        "Hustlers",
        "Queen & Slim",
    ],
    2020: [
        "The Invisible Man",
        "Emma.",
        "Bad Education",
        "Ma Rainey's Black Bottom",
        "News of the World",
        "Possessor",
        "The Vast of Night",
        "Relic",
        "Bacurau",
        "Collective",
        "Shiva Baby",
        "On the Rocks",
        "Herself",
        "Miss Juneteenth",
        "Onward",
        "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
        "The Midnight Sky",
        "Borat Subsequent Moviefilm",
        "The Father",
        "Ammonite",
    ],
    2021: [
        "Free Guy",
        "Cruella",
        "Shang-Chi and the Legend of the Ten Rings",
        "No Sudden Move",
        "The French Dispatch",
        "Zola",
        "Passing",
        "C'mon C'mon",
        "The Card Counter",
        "Benedetta",
        "Annette",
        "Old",
        "The Last Duel",
        "Red Rocket",
        "Flee",
        "Petite Maman",
        "A Hero",
        "House of Gucci",
        "The Tragedy of Macbeth",
        "Don't Look Up",
    ],
    2022: [
        "The Menu",
        "Black Panther: Wakanda Forever",
        "Bones and All",
        "Guillermo del Toro's Pinocchio",
        "Emily the Criminal",
        "Barbarian",
        "X",
        "Marcel the Shell with Shoes On",
        "Turning Red",
        "Athena",
        "Return to Seoul",
        "Corsage",
        "Broker",
        "Close",
        "Empire of Light",
        "Babylon",
        "She Said",
        "Causeway",
        "The Northman",
        "Bodies Bodies Bodies",
    ],
    2023: [
        "Air",
        "John Wick: Chapter 4",
        "Asteroid City",
        "You Hurt My Feelings",
        "Bottoms",
        "A Haunting in Venice",
        "Beau Is Afraid",
        "Napoleon",
        "The Iron Claw",
        "Priscilla",
        "The Killer",
        "Ferrari",
        "Dream Scenario",
        "Monster",
        "The Taste of Things",
        "How to Have Sex",
        "Reality",
        "Passages",
        "Talk to Me",
        "Are You There God? It's Me, Margaret.",
    ],
    2024: [
        "Civil War",
        "Longlegs",
        "Blitz",
        "Gladiator II",
        "Juror #2",
        "Kinds of Kindness",
        "The Room Next Door",
        "Bird",
        "September 5",
        "Small Things Like These",
        "Babygirl",
        "Y2K",
        "Woman of the Hour",
        "Dìdi",
        "Ghostlight",
        "Between the Temples",
        "We Live in Time",
        "His Three Daughters",
        "Hit Man",
        "The Apprentice",
    ],
    2025: [
        "F1",
        "Superman",
        "Mission: Impossible - The Final Reckoning",
        "Companion",
        "The Monkey",
        "The Amateur",
        "Death of a Unicorn",
        "Together",
        "The Naked Gun",
        "Freakier Friday",
        "Elio",
        "KPop Demon Hunters",
        "The Roses",
        "Splitsville",
        "Him",
        "After the Hunt",
        "Christy",
        "Blue Moon",
        "Rental Family",
        "Avatar: Fire and Ash",
    ],
    2026: [
        "Wicked: For Good",
        "Mortal Kombat II",
        "The Devil Wears Prada 2",
        "Now You See Me: Now You Don't",
        "Supergirl: Woman of Tomorrow",
        "Tron: Ares",
        "Predator: Badlands",
        "Roofman",
        "Mercy",
        "Anaconda",
        "Toy Story 5",
        "Shrek 5",
        "Crime 101",
        "Remain",
        "Goat",
        "The Bride!",
        "Flowervale Street",
        "Reminders of Him",
        "Verity",
        "Practical Magic 2",
    ],
}


def norm(title: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", title.lower())


def main() -> None:
    merged: dict[int, list[str]] = {}
    for year in sorted(YEAR_MOVIES):
        existing = list(YEAR_MOVIES[year])
        seen = {norm(t) for t in existing}
        added: list[str] = []
        for title in ADDITIONS.get(year, []):
            key = norm(title)
            if key in seen:
                continue
            seen.add(key)
            added.append(title)
        merged[year] = existing + added
        print(f"{year}: +{len(added)} -> {len(merged[year])} (was {len(existing)})")

    print("TOTAL", sum(len(v) for v in merged.values()))

    lines = [
        '"""Curated 2daymovie library: notable films 2000–2026 (by release year)."""',
        "",
        "YEAR_MOVIES = {",
    ]
    for year in sorted(merged):
        lines.append(f"    {year}: [")
        for title in merged[year]:
            lines.append(f"        {title!r},")
        lines.append("    ],")
    lines.extend(
        [
            "}",
            "",
            "",
            "def all_years():",
            "    return sorted(YEAR_MOVIES.keys(), reverse=True)",
            "",
            "",
            "def titles_for_year(year: int):",
            "    return YEAR_MOVIES.get(year, [])",
            "",
            "",
            "def total_titles():",
            "    return sum(len(v) for v in YEAR_MOVIES.values())",
            "",
        ]
    )
    out = ROOT / "data" / "year_movies.py"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", out)


if __name__ == "__main__":
    main()
